var searchData=
[
  ['identification_7325',['Identification',['../structsf_1_1_joystick_1_1_identification.html',1,'sf::Joystick']]],
  ['image_7326',['Image',['../classsf_1_1_image.html',1,'sf']]],
  ['imboolvector_7327',['ImBoolVector',['../struct_im_bool_vector.html',1,'']]],
  ['imcolor_7328',['ImColor',['../struct_im_color.html',1,'']]],
  ['imdrawchannel_7329',['ImDrawChannel',['../struct_im_draw_channel.html',1,'']]],
  ['imdrawcmd_7330',['ImDrawCmd',['../struct_im_draw_cmd.html',1,'']]],
  ['imdrawdata_7331',['ImDrawData',['../struct_im_draw_data.html',1,'']]],
  ['imdrawdatabuilder_7332',['ImDrawDataBuilder',['../struct_im_draw_data_builder.html',1,'']]],
  ['imdrawlist_7333',['ImDrawList',['../struct_im_draw_list.html',1,'']]],
  ['imdrawlistshareddata_7334',['ImDrawListSharedData',['../struct_im_draw_list_shared_data.html',1,'']]],
  ['imdrawlistsplitter_7335',['ImDrawListSplitter',['../struct_im_draw_list_splitter.html',1,'']]],
  ['imdrawvert_7336',['ImDrawVert',['../struct_im_draw_vert.html',1,'']]],
  ['imdrawvertallegro_7337',['ImDrawVertAllegro',['../struct_im_draw_vert_allegro.html',1,'']]],
  ['imfont_7338',['ImFont',['../struct_im_font.html',1,'']]],
  ['imfontatlas_7339',['ImFontAtlas',['../struct_im_font_atlas.html',1,'']]],
  ['imfontatlascustomrect_7340',['ImFontAtlasCustomRect',['../struct_im_font_atlas_custom_rect.html',1,'']]],
  ['imfontbuilddstdata_7341',['ImFontBuildDstData',['../struct_im_font_build_dst_data.html',1,'']]],
  ['imfontbuilddstdataft_7342',['ImFontBuildDstDataFT',['../struct_im_font_build_dst_data_f_t.html',1,'']]],
  ['imfontbuildsrcdata_7343',['ImFontBuildSrcData',['../struct_im_font_build_src_data.html',1,'']]],
  ['imfontbuildsrcdataft_7344',['ImFontBuildSrcDataFT',['../struct_im_font_build_src_data_f_t.html',1,'']]],
  ['imfontbuildsrcglyphft_7345',['ImFontBuildSrcGlyphFT',['../struct_im_font_build_src_glyph_f_t.html',1,'']]],
  ['imfontconfig_7346',['ImFontConfig',['../struct_im_font_config.html',1,'']]],
  ['imfontglyph_7347',['ImFontGlyph',['../struct_im_font_glyph.html',1,'']]],
  ['imfontglyphrangesbuilder_7348',['ImFontGlyphRangesBuilder',['../struct_im_font_glyph_ranges_builder.html',1,'']]],
  ['imgui_5fimplvulkan_5finitinfo_7349',['ImGui_ImplVulkan_InitInfo',['../struct_im_gui___impl_vulkan___init_info.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframe_7350',['ImGui_ImplVulkanH_Frame',['../struct_im_gui___impl_vulkan_h___frame.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframerenderbuffers_7351',['ImGui_ImplVulkanH_FrameRenderBuffers',['../struct_im_gui___impl_vulkan_h___frame_render_buffers.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframesemaphores_7352',['ImGui_ImplVulkanH_FrameSemaphores',['../struct_im_gui___impl_vulkan_h___frame_semaphores.html',1,'']]],
  ['imgui_5fimplvulkanh_5fwindow_7353',['ImGui_ImplVulkanH_Window',['../struct_im_gui___impl_vulkan_h___window.html',1,'']]],
  ['imgui_5fimplvulkanh_5fwindowrenderbuffers_7354',['ImGui_ImplVulkanH_WindowRenderBuffers',['../struct_im_gui___impl_vulkan_h___window_render_buffers.html',1,'']]],
  ['imguicolormod_7355',['ImGuiColorMod',['../struct_im_gui_color_mod.html',1,'']]],
  ['imguicolumndata_7356',['ImGuiColumnData',['../struct_im_gui_column_data.html',1,'']]],
  ['imguicolumns_7357',['ImGuiColumns',['../struct_im_gui_columns.html',1,'']]],
  ['imguicontext_7358',['ImGuiContext',['../struct_im_gui_context.html',1,'']]],
  ['imguidatatypeinfo_7359',['ImGuiDataTypeInfo',['../struct_im_gui_data_type_info.html',1,'']]],
  ['imguiexampleappdelegate_7360',['ImGuiExampleAppDelegate',['../interface_im_gui_example_app_delegate.html',1,'']]],
  ['imguiexampleview_7361',['ImGuiExampleView',['../interface_im_gui_example_view.html',1,'']]],
  ['imguigroupdata_7362',['ImGuiGroupData',['../struct_im_gui_group_data.html',1,'']]],
  ['imguiinputtextcallbackdata_7363',['ImGuiInputTextCallbackData',['../struct_im_gui_input_text_callback_data.html',1,'']]],
  ['imguiinputtextstate_7364',['ImGuiInputTextState',['../struct_im_gui_input_text_state.html',1,'']]],
  ['imguiio_7365',['ImGuiIO',['../struct_im_gui_i_o.html',1,'']]],
  ['imguiitemhovereddatabackup_7366',['ImGuiItemHoveredDataBackup',['../struct_im_gui_item_hovered_data_backup.html',1,'']]],
  ['imguilistclipper_7367',['ImGuiListClipper',['../struct_im_gui_list_clipper.html',1,'']]],
  ['imguimenucolumns_7368',['ImGuiMenuColumns',['../struct_im_gui_menu_columns.html',1,'']]],
  ['imguinavmoveresult_7369',['ImGuiNavMoveResult',['../struct_im_gui_nav_move_result.html',1,'']]],
  ['imguinextitemdata_7370',['ImGuiNextItemData',['../struct_im_gui_next_item_data.html',1,'']]],
  ['imguinextwindowdata_7371',['ImGuiNextWindowData',['../struct_im_gui_next_window_data.html',1,'']]],
  ['imguionceuponaframe_7372',['ImGuiOnceUponAFrame',['../struct_im_gui_once_upon_a_frame.html',1,'']]],
  ['imguipayload_7373',['ImGuiPayload',['../struct_im_gui_payload.html',1,'']]],
  ['imguiplotarraygetterdata_7374',['ImGuiPlotArrayGetterData',['../struct_im_gui_plot_array_getter_data.html',1,'']]],
  ['imguipopupdata_7375',['ImGuiPopupData',['../struct_im_gui_popup_data.html',1,'']]],
  ['imguiptrorindex_7376',['ImGuiPtrOrIndex',['../struct_im_gui_ptr_or_index.html',1,'']]],
  ['imguiresizegripdef_7377',['ImGuiResizeGripDef',['../struct_im_gui_resize_grip_def.html',1,'']]],
  ['imguisettingshandler_7378',['ImGuiSettingsHandler',['../struct_im_gui_settings_handler.html',1,'']]],
  ['imguisfmlconan_7379',['ImguiSfmlConan',['../classconanfile_1_1_imgui_sfml_conan.html',1,'conanfile']]],
  ['imguishrinkwidthitem_7380',['ImGuiShrinkWidthItem',['../struct_im_gui_shrink_width_item.html',1,'']]],
  ['imguisizecallbackdata_7381',['ImGuiSizeCallbackData',['../struct_im_gui_size_callback_data.html',1,'']]],
  ['imguistorage_7382',['ImGuiStorage',['../struct_im_gui_storage.html',1,'']]],
  ['imguistoragepair_7383',['ImGuiStoragePair',['../struct_im_gui_storage_1_1_im_gui_storage_pair.html',1,'ImGuiStorage']]],
  ['imguistyle_7384',['ImGuiStyle',['../struct_im_gui_style.html',1,'']]],
  ['imguistylemod_7385',['ImGuiStyleMod',['../struct_im_gui_style_mod.html',1,'']]],
  ['imguistylevarinfo_7386',['ImGuiStyleVarInfo',['../struct_im_gui_style_var_info.html',1,'']]],
  ['imguitabbar_7387',['ImGuiTabBar',['../struct_im_gui_tab_bar.html',1,'']]],
  ['imguitabitem_7388',['ImGuiTabItem',['../struct_im_gui_tab_item.html',1,'']]],
  ['imguitextbuffer_7389',['ImGuiTextBuffer',['../struct_im_gui_text_buffer.html',1,'']]],
  ['imguitextfilter_7390',['ImGuiTextFilter',['../struct_im_gui_text_filter.html',1,'']]],
  ['imguitextrange_7391',['ImGuiTextRange',['../struct_im_gui_text_filter_1_1_im_gui_text_range.html',1,'ImGuiTextFilter']]],
  ['imguiwindow_7392',['ImGuiWindow',['../struct_im_gui_window.html',1,'']]],
  ['imguiwindowsettings_7393',['ImGuiWindowSettings',['../struct_im_gui_window_settings.html',1,'']]],
  ['imguiwindowtempdata_7394',['ImGuiWindowTempData',['../struct_im_gui_window_temp_data.html',1,'']]],
  ['imnewdummy_7395',['ImNewDummy',['../struct_im_new_dummy.html',1,'']]],
  ['impool_7396',['ImPool',['../struct_im_pool.html',1,'']]],
  ['impool_3c_20imguitabbar_20_3e_7397',['ImPool&lt; ImGuiTabBar &gt;',['../struct_im_pool.html',1,'']]],
  ['imrect_7398',['ImRect',['../struct_im_rect.html',1,'']]],
  ['imvec1_7399',['ImVec1',['../struct_im_vec1.html',1,'']]],
  ['imvec2_7400',['ImVec2',['../struct_im_vec2.html',1,'']]],
  ['imvec2ih_7401',['ImVec2ih',['../struct_im_vec2ih.html',1,'']]],
  ['imvec4_7402',['ImVec4',['../struct_im_vec4.html',1,'']]],
  ['imvector_7403',['ImVector',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20char_20_2a_20_3e_7404',['ImVector&lt; char * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20char_20_3e_7405',['ImVector&lt; char &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20const_20char_20_2a_20_3e_7406',['ImVector&lt; const char * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20float_20_3e_7407',['ImVector&lt; float &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawchannel_20_3e_7408',['ImVector&lt; ImDrawChannel &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawcmd_20_3e_7409',['ImVector&lt; ImDrawCmd &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawidx_20_3e_7410',['ImVector&lt; ImDrawIdx &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawlist_20_2a_20_3e_7411',['ImVector&lt; ImDrawList * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawvert_20_3e_7412',['ImVector&lt; ImDrawVert &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfont_20_2a_20_3e_7413',['ImVector&lt; ImFont * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontatlascustomrect_20_3e_7414',['ImVector&lt; ImFontAtlasCustomRect &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontbuildsrcglyphft_20_3e_7415',['ImVector&lt; ImFontBuildSrcGlyphFT &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontconfig_20_3e_7416',['ImVector&lt; ImFontConfig &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontglyph_20_3e_7417',['ImVector&lt; ImFontGlyph &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguicolormod_20_3e_7418',['ImVector&lt; ImGuiColorMod &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguicolumndata_20_3e_7419',['ImVector&lt; ImGuiColumnData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguicolumns_20_3e_7420',['ImVector&lt; ImGuiColumns &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguigroupdata_20_3e_7421',['ImVector&lt; ImGuiGroupData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiid_20_3e_7422',['ImVector&lt; ImGuiID &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiitemflags_20_3e_7423',['ImVector&lt; ImGuiItemFlags &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguipopupdata_20_3e_7424',['ImVector&lt; ImGuiPopupData &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiptrorindex_20_3e_7425',['ImVector&lt; ImGuiPtrOrIndex &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguisettingshandler_20_3e_7426',['ImVector&lt; ImGuiSettingsHandler &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguishrinkwidthitem_20_3e_7427',['ImVector&lt; ImGuiShrinkWidthItem &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistorage_3a_3aimguistoragepair_20_3e_7428',['ImVector&lt; ImGuiStorage::ImGuiStoragePair &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistylemod_20_3e_7429',['ImVector&lt; ImGuiStyleMod &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabbar_20_3e_7430',['ImVector&lt; ImGuiTabBar &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabitem_20_3e_7431',['ImVector&lt; ImGuiTabItem &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitextfilter_3a_3aimguitextrange_20_3e_7432',['ImVector&lt; ImGuiTextFilter::ImGuiTextRange &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiwindow_20_2a_20_3e_7433',['ImVector&lt; ImGuiWindow * &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiwindowsettings_20_3e_7434',['ImVector&lt; ImGuiWindowSettings &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imtextureid_20_3e_7435',['ImVector&lt; ImTextureID &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imu32_20_3e_7436',['ImVector&lt; ImU32 &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imvec2_20_3e_7437',['ImVector&lt; ImVec2 &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imvec4_20_3e_7438',['ImVector&lt; ImVec4 &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20imwchar_20_3e_7439',['ImVector&lt; ImWchar &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20int_20_3e_7440',['ImVector&lt; int &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20mydocument_20_3e_7441',['ImVector&lt; MyDocument &gt;',['../struct_im_vector.html',1,'']]],
  ['imvector_3c_20unsigned_20char_20_3e_7442',['ImVector&lt; unsigned char &gt;',['../struct_im_vector.html',1,'']]],
  ['info_7443',['Info',['../structsf_1_1_sound_file_reader_1_1_info.html',1,'sf::SoundFileReader::Info'],['../structsf_1_1_font_1_1_info.html',1,'sf::Font::Info']]],
  ['inputsoundfile_7444',['InputSoundFile',['../classsf_1_1_input_sound_file.html',1,'sf']]],
  ['inputstream_7445',['InputStream',['../classsf_1_1_input_stream.html',1,'sf']]],
  ['inputtextcallback_5fuserdata_7446',['InputTextCallback_UserData',['../struct_input_text_callback___user_data.html',1,'']]],
  ['ipaddress_7447',['IpAddress',['../classsf_1_1_ip_address.html',1,'sf']]]
];
